import { LegalPageLayout, LegalSection, SUPPORT_EMAIL } from "@/components/LegalPageLayout";

export default function Privacy() {
  return (
    <LegalPageLayout title="Privacy Policy">
      <LegalSection heading="1. Overview">
        <p>
          This Privacy Policy explains what information The Lyceum ("we," "us," "our") collects when you
          visit our website, join the waitlist, place a pre-order, or use the Adaptive Audit Engine (the
          "Service"), and how we use, share, and protect it.
        </p>
      </LegalSection>

      <LegalSection heading="2. Information We Collect">
        <p>We collect information in three ways:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            <strong className="text-foreground">Information you provide.</strong> Name, email address,
            organization, and any details you enter when pre-ordering, joining the waitlist, or contacting
            support.
          </li>
          <li>
            <strong className="text-foreground">Payment information.</strong> Pre-order payments are
            processed entirely by Lemon Squeezy, our payment processor and merchant of record. We do not
            receive or store your full card number — Lemon Squeezy handles that in accordance with its own
            privacy policy.
          </li>
          <li>
            <strong className="text-foreground">Usage information.</strong> Content you submit to the
            Service for processing, license-key-linked usage and task history, and standard technical logs
            (IP address, browser type, timestamps) generated by using the website and API.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="3. How We Use Information">
        <ul className="list-disc pl-5 space-y-1.5">
          <li>To provision and operate your license key, quota, and account;</li>
          <li>To process pre-orders and send order/waiting-room status updates;</li>
          <li>To provide, maintain, and improve the Service, including debugging and abuse prevention;</li>
          <li>To respond to support requests sent to {SUPPORT_EMAIL};</li>
          <li>To send you product updates you've opted into (e.g. beta access notifications).</li>
        </ul>
      </LegalSection>

      <LegalSection heading="4. Third-Party Service Providers">
        <p>We rely on the following processors to operate the Service. Each processes data under its own privacy terms:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            <strong className="text-foreground">Lemon Squeezy</strong> — payment processing and checkout.
          </li>
          <li>
            <strong className="text-foreground">Google Firebase / Firestore</strong> — storage of account,
            quota, and task-history data.
          </li>
          <li>
            <strong className="text-foreground">OpenRouter</strong> and its underlying model providers
            (e.g. Anthropic, OpenAI, Google) — processing of content you submit to AI domains for analysis.
          </li>
          <li>
            <strong className="text-foreground">Supabase</strong> — auxiliary application data storage.
          </li>
          <li>
            <strong className="text-foreground">Vercel</strong> — application hosting and infrastructure.
          </li>
        </ul>
        <p>
          We do not sell your personal information. We share it with these providers only as needed to
          operate the Service, and with law enforcement or other third parties only where required by law.
        </p>
      </LegalSection>

      <LegalSection heading="5. Data Retention">
        <p>
          We retain account, quota, and task-history data for as long as your license key is active and for
          a reasonable period afterward for support, accounting, and legal-compliance purposes. You can
          request deletion of your data as described in Section 7 below.
        </p>
      </LegalSection>

      <LegalSection heading="6. Cookies">
        <p>
          Our website uses only the cookies/local storage necessary for core functionality (e.g. remembering
          your session in the admin dashboard). We do not use third-party advertising trackers.
        </p>
      </LegalSection>

      <LegalSection heading="7. Your Rights">
        <p>
          Depending on where you live, you may have the right to access, correct, export, or delete your
          personal information, or to object to certain processing. To exercise any of these rights, email{" "}
          <a href={`mailto:${SUPPORT_EMAIL}`} className="text-teal hover:text-teal-dark underline underline-offset-2">
            {SUPPORT_EMAIL}
          </a>{" "}
          and we'll respond within a reasonable timeframe.
        </p>
      </LegalSection>

      <LegalSection heading="8. Data Security">
        <p>
          We use industry-standard measures — including encrypted transport, access-controlled databases,
          and secret management — to protect your information. No method of transmission or storage is
          100% secure, and we cannot guarantee absolute security.
        </p>
      </LegalSection>

      <LegalSection heading="9. Children's Privacy">
        <p>The Service is intended for business use by adults and is not directed at children under 16. We do not knowingly collect personal information from children.</p>
      </LegalSection>

      <LegalSection heading="10. Changes to This Policy">
        <p>
          We may update this Privacy Policy as the Service evolves. Material changes will be reflected by
          updating the effective date above.
        </p>
      </LegalSection>

      <LegalSection heading="11. Contact">
        <p>
          Questions about this Privacy Policy or your data? Reach us at{" "}
          <a href={`mailto:${SUPPORT_EMAIL}`} className="text-teal hover:text-teal-dark underline underline-offset-2">
            {SUPPORT_EMAIL}
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
}
