/**
 * ClarificationSidebar — Unanswered AI pre-task Questions
 *
 * Shows all unanswered clarification questions (generated by AI after
 * reading task docs) grouped by task. The human manager answers MCQs
 * or types free text for the "Other" option. Once all questions for
 * a task are answered, the AI proceeds with execution.
 */

import { useState, useEffect, useCallback, useRef } from "react";
import { HelpCircle, Send, CheckCircle2, ChevronDown, MessageSquare, Clock, History } from "lucide-react";
import { useSessionStore } from "@/store/useSessionStore";
import type { ClarificationQuestion } from "@/lib/clarificationQuestions";

export default function ClarificationSidebar() {
  const unanswered = useSessionStore((s) => s.getAllUnansweredQuestions());
  const answerQuestion = useSessionStore((s) => s.answerClarificationQuestion);
  const autoAnswerEnabled = useSessionStore((s) => s.autoAnswerEnabled);
  const autoAnswerTimeout = useSessionStore((s) => s.autoAnswerTimeout);
  const autoAnswerAuditLog = useSessionStore((s) => s.autoAnswerAuditLog);
  const getRemaining = useSessionStore((s) => s.getAutoAnswerRemainingMs);

  if (unanswered.length === 0 && autoAnswerAuditLog.length === 0) return null;

  const totalQuestions = unanswered.reduce((sum, g) => sum + g.questions.length, 0);

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        borderTop: "1px solid rgba(255,255,255,0.06)",
      }}
    >
      {/* Header */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 6,
          padding: "8px 12px",
          borderBottom: "1px solid rgba(255,255,255,0.06)",
        }}
      >
        <HelpCircle style={{ width: 12, height: 12, color: "#f59e0b", flexShrink: 0 }} />
        <span
          style={{
            fontFamily: "'Inter', sans-serif",
            fontSize: 9,
            fontWeight: 600,
            color: "#f59e0b",
            textTransform: "uppercase",
            letterSpacing: "0.06em",
          }}
        >
          {totalQuestions > 0
            ? `${totalQuestions} question${totalQuestions > 1 ? "s" : ""} need answers`
            : "Auto-answers"}
        </span>
      </div>

      {/* Groups by task */}
      <div
        style={{
          flex: 1,
          overflowY: "auto",
          padding: "6px 8px",
        }}
      >
        {unanswered.map((group) => (
          <TaskQuestionGroup
            key={group.taskId}
            taskTitle={group.taskTitle}
            questions={group.questions}
            onAnswer={(questionId, answer) => answerQuestion(group.taskId, questionId, answer)}
            autoAnswerEnabled={autoAnswerEnabled}
            autoAnswerTimeout={autoAnswerTimeout}
            getRemainingMs={() => getRemaining(group.taskId)}
          />
        ))}

        {/* Audit log section (shows if there are auto-answered questions) */}
        {autoAnswerAuditLog.length > 0 && (
          <AuditLogSection entries={autoAnswerAuditLog} />
        )}
      </div>
    </div>
  );
}

// ── Auto-answer countdown ────────────────────────────────────────────────────

function AutoAnswerCountdown({
  getRemainingMs,
  onExpired,
}: {
  getRemainingMs: () => number;
  onExpired: () => void;
}) {
  const [remaining, setRemaining] = useState(getRemainingMs());
  const expiredRef = useRef(false);

  useEffect(() => {
    // If already expired on mount, just show nothing — don't call onExpired
    if (remaining <= 0) return;

    const interval = setInterval(() => {
      const next = getRemainingMs();
      if (next <= 0 && !expiredRef.current) {
        expiredRef.current = true;
        clearInterval(interval);
        onExpired();
        setRemaining(0);
        return;
      }
      setRemaining(next);
    }, 1000);

    return () => clearInterval(interval);
    // Stable deps: getRemainingMs is from Zustand (stable selector), onExpired from useCallback
  }, [getRemainingMs, onExpired]);

  if (remaining <= 0) return null;

  const seconds = Math.ceil(remaining / 1000);
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;

  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: 4,
        marginTop: 4,
        padding: "3px 6px",
        borderRadius: 4,
        background: "rgba(245,158,11,0.08)",
        border: "1px solid rgba(245,158,11,0.15)",
      }}
    >
      <Clock style={{ width: 8, height: 8, color: "#f59e0b", flexShrink: 0 }} />
      <span
        style={{
          fontFamily: "'Inter', sans-serif",
          fontSize: 7,
          color: "#f59e0b",
          fontWeight: 500,
        }}
      >
        Auto-answer in {mins}:{secs.toString().padStart(2, "0")}
      </span>
    </div>
  );
}

// ── Audit Log Section ────────────────────────────────────────────────────────

function AuditLogSection({ entries }: { entries: { taskTitle: string; question: string; defaultAnswer: string; timestamp: number }[] }) {
  const [open, setOpen] = useState(false);
  // Show only the 10 most recent entries
  const recent = entries.slice(-10).reverse();

  return (
    <div
      style={{
        marginTop: 8,
        padding: "6px 8px",
        borderRadius: 8,
        background: "rgba(59,130,246,0.04)",
        border: "1px solid rgba(59,130,246,0.1)",
      }}
    >
      <button
        onClick={() => setOpen(!open)}
        style={{
          display: "flex",
          alignItems: "center",
          gap: 5,
          width: "100%",
          background: "none",
          border: "none",
          cursor: "pointer",
          textAlign: "left",
          padding: 0,
        }}
      >
        <History style={{ width: 10, height: 10, color: "#3b82f6", flexShrink: 0 }} />
        <span
          style={{
            fontFamily: "'Inter', sans-serif",
            fontSize: 8,
            fontWeight: 600,
            color: "#3b82f6",
            letterSpacing: "0.03em",
            flex: 1,
          }}
        >
          Assumed Defaults ({entries.length})
        </span>
        <ChevronDown
          style={{
            width: 8,
            height: 8,
            color: "rgba(255,255,255,0.3)",
            transform: open ? "rotate(0deg)" : "rotate(-90deg)",
            transition: "transform 0.2s ease",
          }}
        />
      </button>

      {open && (
        <div style={{ marginTop: 6, display: "flex", flexDirection: "column", gap: 4 }}>
          {recent.map((entry, i) => {
            const time = new Date(entry.timestamp);
            return (
              <div
                key={i}
                style={{
                  padding: "4px 6px",
                  borderRadius: 4,
                  background: "rgba(0,0,0,0.15)",
                  fontSize: 7,
                  fontFamily: "'Inter', sans-serif",
                }}
              >
                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 2 }}>
                  <span style={{ color: "rgba(255,255,255,0.5)", fontWeight: 500 }}>
                    {entry.taskTitle}
                  </span>
                  <span style={{ color: "rgba(255,255,255,0.3)" }}>
                    {time.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                  </span>
                </div>
                <div style={{ color: "rgba(255,255,255,0.65)", lineHeight: 1.4 }}>
                  {entry.question}
                </div>
                <div style={{ color: "#3b82f6", marginTop: 1 }}>
                  → Assumed: <strong>{entry.defaultAnswer}</strong>
                </div>
              </div>
            );
          })}
          {entries.length > 10 && (
            <div style={{ textAlign: "center", fontSize: 7, color: "rgba(255,255,255,0.3)", marginTop: 2 }}>
              +{entries.length - 10} more
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ── Task Question Group (updated with countdown) ─────────────────────────────

// ── Task Question Group ──────────────────────────────────────────────────────

function TaskQuestionGroup({
  taskTitle,
  questions,
  onAnswer,
  autoAnswerEnabled,
  autoAnswerTimeout,
  getRemainingMs,
}: {
  taskTitle: string;
  questions: ClarificationQuestion[];
  onAnswer: (questionId: string, answer: string) => void;
  autoAnswerEnabled: boolean;
  autoAnswerTimeout: number;
  getRemainingMs: () => number;
}) {
  const [collapsed, setCollapsed] = useState(false);

  return (
    <div
      style={{
        marginBottom: 6,
        background: "rgba(245,158,11,0.04)",
        borderRadius: 8,
        border: "1px solid rgba(245,158,11,0.1)",
        overflow: "hidden",
      }}
    >
      {/* Task header (collapsible) */}
      <button
        onClick={() => setCollapsed(!collapsed)}
        style={{
          display: "flex",
          alignItems: "center",
          gap: 6,
          width: "100%",
          padding: "6px 8px",
          background: "none",
          border: "none",
          cursor: "pointer",
          textAlign: "left",
        }}
      >
        <MessageSquare style={{ width: 10, height: 10, color: "rgba(255,255,255,0.3)", flexShrink: 0 }} />
        <span
          style={{
            fontFamily: "'Inter', sans-serif",
            fontSize: 9,
            fontWeight: 500,
            color: "rgba(255,255,255,0.7)",
            flex: 1,
            overflow: "hidden",
            textOverflow: "ellipsis",
            whiteSpace: "nowrap",
          }}
        >
          {taskTitle}
        </span>
        <span
          style={{
            fontFamily: "'Inter', sans-serif",
            fontSize: 7,
            color: "#f59e0b",
            fontWeight: 500,
            background: "rgba(245,158,11,0.15)",
            padding: "1px 5px",
            borderRadius: 4,
          }}
        >
          {questions.length}
        </span>
        <ChevronDown
          style={{
            width: 10,
            height: 10,
            color: "rgba(255,255,255,0.2)",
            flexShrink: 0,
            transform: collapsed ? "rotate(-90deg)" : "none",
            transition: "transform 0.2s ease",
          }}
        />
      </button>

      {/* Auto-answer countdown */}
      {autoAnswerEnabled && autoAnswerTimeout > 0 && !collapsed && (
        <AutoAnswerCountdown getRemainingMs={getRemainingMs} onExpired={() => {}} />
      )}

      {/* Questions */}
      {!collapsed && (
        <div style={{ padding: "0 8px 8px" }}>
          {questions.map((q) => (
            <QuestionItem key={q.id} question={q} onAnswer={onAnswer} />
          ))}
        </div>
      )}
    </div>
  );
}

// ── Question Item ───────────────────────────────────────────────────────────

function QuestionItem({
  question,
  onAnswer,
}: {
  question: ClarificationQuestion;
  onAnswer: (questionId: string, answer: string) => void;
}) {
  const [customText, setCustomText] = useState("");
  const [showCustom, setShowCustom] = useState(false);
  const [selected, setSelected] = useState<string | null>(null);

  const handleSelect = (optionId: string, optionText: string) => {
    if (optionId.endsWith("-other")) {
      setShowCustom(true);
      setSelected(optionId);
    } else {
      setSelected(optionId);
      setShowCustom(false);
      onAnswer(question.id, optionId);
    }
  };

  const handleCustomSubmit = () => {
    if (!customText.trim()) return;
    onAnswer(question.id, customText.trim());
  };

  return (
    <div
      style={{
        marginTop: 6,
        padding: "6px 8px",
        background: "rgba(0,0,0,0.15)",
        borderRadius: 6,
      }}
    >
      {/* Question text */}
      <p
        style={{
          fontFamily: "'Inter', sans-serif",
          fontSize: 9,
          color: "rgba(255,255,255,0.75)",
          lineHeight: 1.5,
          marginBottom: 6,
        }}
      >
        {question.question}
      </p>

      {/* Options */}
      <div style={{ display: "flex", flexDirection: "column", gap: 3 }}>
        {question.options.map((opt) => {
          const isSelected = selected === opt.id && !showCustom;
          const isOther = opt.id.endsWith("-other");
          return (
            <button
              key={opt.id}
              onClick={() => handleSelect(opt.id, opt.text)}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 5,
                padding: "4px 6px",
                borderRadius: 4,
                border: `1px solid ${
                  isSelected ? "rgba(245,158,11,0.4)" : "rgba(255,255,255,0.06)"
                }`,
                background: isSelected
                  ? "rgba(245,158,11,0.1)"
                  : "transparent",
                cursor: "pointer",
                textAlign: "left",
                transition: "all 0.15s ease",
              }}
              onMouseEnter={(e) => {
                if (!isSelected) (e.currentTarget).style.borderColor = "rgba(255,255,255,0.15)";
              }}
              onMouseLeave={(e) => {
                if (!isSelected) (e.currentTarget).style.borderColor = "rgba(255,255,255,0.06)";
              }}
            >
              <span
                style={{
                  width: 8,
                  height: 8,
                  borderRadius: "50%",
                  border: `1.5px solid ${
                    isSelected ? "#f59e0b" : "rgba(255,255,255,0.2)"
                  }`,
                  background: isSelected ? "#f59e0b" : "transparent",
                  flexShrink: 0,
                  transition: "all 0.15s ease",
                }}
              />
              <span
                style={{
                  fontFamily: "'Inter', sans-serif",
                  fontSize: 8,
                  color: isSelected
                    ? "rgba(255,255,255,0.85)"
                    : isOther
                      ? "rgba(245,158,11,0.6)"
                      : "rgba(255,255,255,0.55)",
                  lineHeight: 1.3,
                }}
              >
                {opt.text}
              </span>
            </button>
          );
        })}
      </div>

      {/* Custom text input (for "Other") */}
      {showCustom && (
        <div style={{ display: "flex", gap: 4, marginTop: 6 }}>
          <input
            type="text"
            value={customText}
            onChange={(e) => setCustomText(e.target.value)}
            placeholder="Type your answer..."
            style={{
              flex: 1,
              padding: "4px 6px",
              borderRadius: 4,
              border: "1px solid rgba(245,158,11,0.25)",
              background: "rgba(0,0,0,0.2)",
              color: "rgba(255,255,255,0.8)",
              fontSize: 8,
              fontFamily: "'Inter', sans-serif",
              outline: "none",
            }}
            autoFocus
            onKeyDown={(e) => {
              if (e.key === "Enter") handleCustomSubmit();
            }}
          />
          <button
            onClick={handleCustomSubmit}
            disabled={!customText.trim()}
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              padding: "4px 8px",
              borderRadius: 4,
              border: "none",
              background: customText.trim() ? "#f59e0b" : "rgba(255,255,255,0.06)",
              color: customText.trim() ? "#111" : "rgba(255,255,255,0.2)",
              cursor: customText.trim() ? "pointer" : "default",
              fontSize: 8,
              fontFamily: "'Inter', sans-serif",
              fontWeight: 500,
              transition: "all 0.15s ease",
            }}
          >
            <Send style={{ width: 10, height: 10 }} />
          </button>
        </div>
      )}

      {/* Answered indicator */}
      {!showCustom && selected && (
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 3,
            marginTop: 4,
            fontSize: 7,
            color: "#22c55e",
            fontFamily: "'Inter', sans-serif",
          }}
        >
          <CheckCircle2 style={{ width: 8, height: 8 }} />
          Answered
        </div>
      )}
    </div>
  );
}
