/**
 * Session Store — The Lyceum
 *
 * Manages task onboarding sessions:
 *   1. User selects tasks (AI-suggested + custom)
 *   2. Sets timeframes for each task
 *   3. Assigns AI agents by role to serve each task
 *   4. Confirms → workspace starts
 *   5. Human→AI dependency: when human completes a task, the output triggers the AI
 *
 * This is separate from useWorkforceStore (which manages the canvas/graph)
 * and useWorkspaceStore (which manages files/folders).
 */

import { create } from "zustand";
import { persist } from "zustand/middleware";
import { runAgent as runAgentFn } from "@/services/agentRunner";
import { generateQuestionsForTask } from "@/lib/clarificationQuestions";
import type { ClarificationQuestion, ClarificationOption, AutoAnswerAuditEntry } from "@/lib/clarificationQuestions";
import { getDefaultOptionId, getDefaultAnswerForQuestion } from "@/lib/clarificationQuestions";

// Re-export types for consumers
import type { StreamChunk } from "@/services/agentRunner";
export type { StreamChunk };
export type { ClarificationQuestion, ClarificationOption, AutoAnswerAuditEntry };

// ── Types ────────────────────────────────────────────────────────────────────

export type TaskCategory = 
  | "data_annotation" | "data_collection" | "audio_speech" 
  | "explainable_ai" | "content_generation" | "code_development"
  | "market_research" | "customer_support" | "qa_testing"
  | "design" | "operations" | "custom";

export type TaskStatus = "not_started" | "in_progress" | "awaiting_ai" | "ai_working" | "completed" | "blocked" | "failed" | "awaiting_approval" | "awaiting_clarification";

export type AssigneeType = "human" | "ai";

export interface TaskRoleAI {
  /** Role name (e.g. "Data Extraction", "Code Generation") */
  roleName: string;
  /** Which AI agent node ID handles this role */
  agentNodeId: string;
  /** Which domain model to use */
  domain: string;
  /** Whether this AI requires human output before triggering */
  requiresHumanOutput: boolean;
}

export interface SelectedTask {
  id: string;
  /** Title of the task */
  title: string;
  /** Category */
  category: TaskCategory;
  /** Description */
  description: string;
  /** Whether this was AI-suggested or user-created */
  source: "ai_suggested" | "custom";
  /** Timeframe set by user */
  timeframe: string;
  /** Estimated duration in minutes */
  estimatedMinutes: number;
  /** Which AI roles are assigned to this task */
  assignedAIs: TaskRoleAI[];
  /** Current status */
  status: TaskStatus;
  /** Order in the workflow (1-based) */
  order: number;
  /** IDs of tasks that must complete before this one can start */
  dependsOn: string[];
  /** Human output (set when human completes their part) */
  humanOutput?: string;
  /** AI output (set when AI completes) — legacy single field */
  aiOutput?: string;
  /** Per-role AI outputs, keyed by roleName (for multi-agent tasks) */
  aiOutputs?: Record<string, string>;
  // ── Retry-limit fields ──────────────────────────────────────────────────
  /** How many times this task has been attempted */
  attemptCount?: number;
  /** Error message from the last failure */
  error?: string;
  /** Pending human approval request (if status is 'awaiting_approval') */
  approvalRequest?: {
    id: string;
    errorContext: string;
    requestedAction: string;
    status: "pending" | "approved" | "rejected";
    failedAttemptNumber: number;
  };
  // ── Pre-execution clarification questions ───────────────────────────────
  /** Questions the AI generated by reading the task docs, awaiting human answers */
  clarificationQuestions?: ClarificationQuestion[];
}

// ── Clarification Store Actions ──────────────────────────────────────────────

export type ClarificationActions = {
  /** Generate clarification questions for a task (AI reads docs → produces MCQ) */
  generateClarificationQuestions: (taskId: string) => void;
  /** Answer a clarification question (option click or free text submit) */
  answerClarificationQuestion: (taskId: string, questionId: string, answer: string) => void;
  /** Get unanswered questions for a task */
  getUnansweredQuestions: (taskId: string) => ClarificationQuestion[];
  /** Get ALL unanswered questions across all tasks */
  getAllUnansweredQuestions: () => { taskId: string; taskTitle: string; questions: ClarificationQuestion[] }[];
};

export interface TaskSession {
  id: string;
  /** Session name */
  name: string;
  /** When the session was created */
  createdAt: number;
  /** Selected tasks */
  tasks: SelectedTask[];
  /** Whether the session has been confirmed */
  confirmed: boolean;
  /** Whether the session is currently active */
  active: boolean;
  /** Current task being worked on */
  activeTaskId: string | null;
}

// ── AI-Suggested Tasks (seeded from the Organizer AI) ────────────────────────

export const SUGGESTED_TASKS: Omit<SelectedTask, "id" | "status" | "order" | "dependsOn" | "humanOutput" | "aiOutput" | "timeframe" | "estimatedMinutes" | "assignedAIs" | "source">[] = [
  {
    title: "Data Annotation Pipeline",
    category: "data_annotation",
    description: "Set up multimodal annotation workflows for image, video, and 3D data with quality control gates.",
  },
  {
    title: "Data Collection Campaign",
    category: "data_collection",
    description: "Deploy collection pipelines across multiple regions to capture and structure real-world datasets.",
  },
  {
    title: "Audio Transcription System",
    category: "audio_speech",
    description: "Build automation-first audio transcription with human validation and scalable processing.",
  },
  {
    title: "Explainable AI Dashboard",
    category: "explainable_ai",
    description: "Create transparent AI models with interpretable predictions and decision-making insights.",
  },
  {
    title: "Content Generation Workflow",
    category: "content_generation",
    description: "AI-powered content creation pipeline with human review gates and brand compliance checks.",
  },
  {
    title: "Feature Development Sprint",
    category: "code_development",
    description: "End-to-end feature development with AI code generation, human review, and automated testing.",
  },
  {
    title: "Market Research Analysis",
    category: "market_research",
    description: "AI-driven competitive analysis with structured data extraction and insight generation.",
  },
  {
    title: "Customer Support Automation",
    category: "customer_support",
    description: "Intelligent ticket routing, response generation, and escalation workflows.",
  },
  {
    title: "QA Testing Suite",
    category: "qa_testing",
    description: "Automated test generation, execution, and regression analysis with AI auditors.",
  },
];

// ── AI Roles Available for Assignment ────────────────────────────────────────

export const AVAILABLE_AI_ROLES: Omit<TaskRoleAI, "agentNodeId">[] = [
  { roleName: "Data Extraction Specialist", domain: "TECH", requiresHumanOutput: true },
  { roleName: "Code Generation Specialist", domain: "TECH", requiresHumanOutput: true },
  { roleName: "Content Creator", domain: "MUSE", requiresHumanOutput: false },
  { roleName: "Legal Analyst", domain: "LAW", requiresHumanOutput: true },
  { roleName: "Financial Analyst", domain: "FINANCE", requiresHumanOutput: true },
  { roleName: "Quality Auditor", domain: "TECH", requiresHumanOutput: false },
  { roleName: "Research Assistant", domain: "TECH", requiresHumanOutput: false },
  { roleName: "Executive Strategist", domain: "LAW", requiresHumanOutput: true },
];

// ── Store Interface ───────────────────────────────────────────────────────────

interface SessionStore {
  // Server sync state
  serverSyncStatus: "idle" | "syncing" | "error";
  serverSyncError: string | null;
  
  // License key for server auth
  licenseKey: string | null;
  setLicenseKey: (key: string) => void;
  // Current session
  currentSession: TaskSession | null;
  
  // Wizard state
  step: "platform_select" | "task_select" | "ai_assign" | "confirm" | "workspace";
  
  // Actions
  setStep: (step: SessionStore["step"]) => void;
  createSession: (name: string) => void;
  addTask: (task: Omit<SelectedTask, "id" | "status" | "order" | "dependsOn" | "humanOutput" | "aiOutput">) => void;
  removeTask: (taskId: string) => void;
  updateTaskTimeframe: (taskId: string, timeframe: string) => void;
  assignAIToTask: (taskId: string, aiRole: TaskRoleAI) => void;
  removeAITask: (taskId: string, roleName: string) => void;
  addTaskDependency: (taskId: string, dependsOnId: string) => void;
  removeTaskDependency: (taskId: string, dependsOnId: string) => void;
  confirmSession: () => void;
  
  // Server sync
  syncSessionToServer: () => Promise<void>;
  loadServerSessions: () => Promise<void>;
  confirmSessionAndSync: () => Promise<void>;
  
  // Workspace actions
  setActiveTask: (taskId: string | null) => void;
  submitHumanOutput: (taskId: string, output: string) => void;
  completeTask: (taskId: string) => void;
  triggerAITask: (taskId: string) => Promise<void>;
  triggerAIAgent: (taskId: string, roleName: string) => Promise<string>;
  updateTaskAIOutput: (taskId: string, roleName: string, text: string) => void;
  updateTaskStatus: (taskId: string, status: TaskStatus) => void;
  setSessionActive: (active: boolean) => void;
  // ── Retry & approval actions ───────────────────────────────────────────
  /** Current attempt count for a task (increments on each run) */
  getTaskAttempts: (taskId: string) => number;
  /** Increment attempt count for a task */
  incrementTaskAttempt: (taskId: string) => void;
  /** Mark task as failed and await human approval */
  markTaskFailed: (taskId: string, error: string) => void;
  /** Approve a retry (human clicked "retry") */
  approveRetry: (taskId: string) => void;
  /** Reject a retry (human clicked "dismiss") */
  rejectRetry: (taskId: string) => void;
  /** Max attempts before permanent failure */
  maxAttempts: number;
  /** Set max attempts config */
  setMaxAttempts: (n: number) => void;
  
  // Session history
  sessions: TaskSession[];
  
  // Session history actions
  loadSession: (sessionId: string) => void;
  deleteSession: (sessionId: string) => void;
  
  // Clarification questions
  generateClarificationQuestions: (taskId: string) => void;
  answerClarificationQuestion: (taskId: string, questionId: string, answer: string) => void;
  getUnansweredQuestions: (taskId: string) => ClarificationQuestion[];
  getAllUnansweredQuestions: () => { taskId: string; taskTitle: string; questions: ClarificationQuestion[] }[];

  // ── Auto-answer config & audit ────────────────────────────────────────
  /** Whether auto-answer mode is enabled */
  autoAnswerEnabled: boolean;
  /** Timeout in ms before auto-answer fires (default: 5 minutes) */
  autoAnswerTimeout: number;
  /** Audit log of auto-answered questions */
  autoAnswerAuditLog: AutoAnswerAuditEntry[];
  /** Set auto-answer config */
  setAutoAnswerConfig: (config: { enabled?: boolean; timeoutMs?: number }) => void;
  /** Start the auto-answer timer for a task (called when questions are generated) */
  startAutoAnswerTimer: (taskId: string) => void;
  /** Cancel auto-answer timer for a task (called when human starts answering) */
  cancelAutoAnswerTimer: (taskId: string) => void;
  /** Force auto-answer all unanswered questions for a task now */
  autoAnswerUnanswered: (taskId: string) => void;
  /** Get the remaining ms before auto-answer fires for a task (0 if no timer) */
  getAutoAnswerRemainingMs: (taskId: string) => number;

  // Query helpers
  getTaskById: (taskId: string) => SelectedTask | undefined;
  getHumanTasks: () => SelectedTask[];
  getAITasks: () => SelectedTask[];
  getTasksReadyForHuman: () => SelectedTask[];
  getDependentTasks: (taskId: string) => SelectedTask[];
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Strip client-only fields for server serialization. */
function stripForServer(task: SelectedTask) {
  return {
    id: task.id,
    title: task.title,
    category: task.category,
    description: task.description,
    source: task.source,
    timeframe: task.timeframe,
    estimatedMinutes: task.estimatedMinutes,
    assignedAIs: task.assignedAIs,
    status: task.status,
    order: task.order,
    dependsOn: task.dependsOn,
    humanOutput: task.humanOutput,
    aiOutput: task.aiOutput,
    aiOutputs: task.aiOutputs,
    // Persist clarification questions and answers
    clarificationQuestions: task.clarificationQuestions,
    // Persist retry-limit state
    attemptCount: task.attemptCount,
    error: task.error,
    approvalRequest: task.approvalRequest,
  };
}

function syncSessions(sessions: TaskSession[], current: TaskSession | null): TaskSession[] {
  if (!current) return sessions;
  const idx = sessions.findIndex((s) => s.id === current.id);
  if (idx >= 0) {
    const updated = [...sessions];
    updated[idx] = current;
    return updated;
  }
  return [...sessions, current];
}

// ── Auto-answer timer map (module-level, not persisted) ─────────────────────

/**
 * Maps taskId → { timerId, startTime, durationMs }
 * Timers are stored at module level so they survive store re-renders.
 */
const autoAnswerTimers = new Map<string, {
  timerId: ReturnType<typeof setTimeout>;
  startTime: number;
  durationMs: number;
}>();

// ── Store ────────────────────────────────────────────────────────────────────

const STORAGE_KEY = "lyceum-sessions";

export const useSessionStore = create<SessionStore>()(
  persist(
    (set, get) => ({
  currentSession: null,
  sessions: [],
  step: "platform_select",
  serverSyncStatus: "idle",
  serverSyncError: null,
  licenseKey: null,
  maxAttempts: 2,
  autoAnswerEnabled: true,
  autoAnswerTimeout: 300000, // 5 minutes
  autoAnswerAuditLog: [],

      setLicenseKey: (key) => set({ licenseKey: key }),

      setStep: (step) => set({ step }),
      setMaxAttempts: (n) => set({ maxAttempts: Math.max(1, Math.min(5, n)) }),

      getTaskAttempts: (taskId) => {
        const task = get().currentSession?.tasks.find((t) => t.id === taskId);
        return task?.attemptCount ?? 0;
      },

      incrementTaskAttempt: (taskId) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId ? { ...t, attemptCount: (t.attemptCount ?? 0) + 1 } : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      markTaskFailed: (taskId, error) => {
        const session = get().currentSession;
        if (!session) return;
        const max = get().maxAttempts;
        const task = session.tasks.find((t) => t.id === taskId);
        // attemptCount was already incremented by triggerAITask/triggerAIAgent,
        // so we use the current value directly (not +1)
        const attempts = task?.attemptCount ?? 1;

        const needsApproval = attempts < max;
        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId
              ? {
                  ...t,
                  status: needsApproval ? "awaiting_approval" as TaskStatus : "failed" as TaskStatus,
                  error,
                  attemptCount: attempts,
                  ...(needsApproval ? {
                    approvalRequest: {
                      id: `approval-${taskId}-${attempts}`,
                      errorContext: error,
                      requestedAction: `Retry task "${t.title}"`,
                      status: "pending" as const,
                      failedAttemptNumber: attempts,
                    },
                  } : {}),
                }
              : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });

        // If max attempts exhausted, broadcast a notification
        if (!needsApproval) {
          console.warn(`[Lyceum] Task ${taskId} permanently failed after ${max} attempts: ${error}`);
        }
      },

      approveRetry: (taskId) => {
        const session = get().currentSession;
        if (!session) return;
        // Clear error, reset to in_progress (if human task) or awaiting_ai (if AI task)
        const task = session.tasks.find((t) => t.id === taskId);
        if (!task) return;
        const hasAI = task.assignedAIs.length > 0;
        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId
              ? {
                  ...t,
                  status: hasAI ? "awaiting_ai" as TaskStatus : "in_progress" as TaskStatus,
                  error: undefined,
                  approvalRequest: undefined,
                  // Keep attemptCount so the next run knows how many attempts we've used
                }
              : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      rejectRetry: (taskId) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId
              ? {
                  ...t,
                  status: "blocked" as TaskStatus,
                  approvalRequest: {
                    ...t.approvalRequest!,
                    status: "rejected" as const,
                  },
                }
              : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      createSession: (name) => {
        const oldSession = get().currentSession;
        const oldSessions = oldSession
          ? syncSessions(get().sessions, oldSession)
          : get().sessions;

        const session: TaskSession = {
          id: `session-${Date.now()}`,
          name,
          createdAt: Date.now(),
          tasks: [],
          confirmed: false,
          active: false,
          activeTaskId: null,
        };
        set({
          currentSession: session,
          sessions: oldSessions,
          step: "task_select",
        });
      },

      loadSession: (sessionId) => {
        const target = get().sessions.find((s) => s.id === sessionId);
        if (!target) return;
        // Save the current session before switching
        const current = get().currentSession;
        const sessions = current
          ? syncSessions(get().sessions, current)
          : get().sessions;

        // Restore audit log from the stored session data
        const auditLog = (target as any).autoAnswerAuditLog;
        const patch: Partial<SessionStore> = {
          currentSession: { ...target, active: true },
          sessions,
          step: target.confirmed ? "workspace" : "task_select",
        };
        if (auditLog) {
          patch.autoAnswerAuditLog = auditLog;
        }

        set(patch);
      },

      deleteSession: (sessionId) => {
        const current = get().currentSession;
        const sessions = get().sessions.filter((s) => s.id !== sessionId);
        // If we're deleting the active session, also clear currentSession
        const clearCurrent = current?.id === sessionId;
        set({
          sessions,
          currentSession: clearCurrent ? null : current,
          step: clearCurrent ? "platform_select" : get().step,
        });
      },

      addTask: (task) => {
        const session = get().currentSession;
        if (!session) return;
        
        // Auto-wire sequential dependency: new task depends on the last added task
        const lastTask = session.tasks[session.tasks.length - 1];
        const autoDependsOn = lastTask ? [lastTask.id] : [];

        const newTask: SelectedTask = {
          ...task,
          id: `task-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
          status: "not_started",
          order: session.tasks.length + 1,
          dependsOn: autoDependsOn,
          humanOutput: undefined,
          aiOutput: undefined,
          aiOutputs: {},
        };
        
        const updated = { ...session, tasks: [...session.tasks, newTask] };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      // Server sync — persist session to Firestore
      syncSessionToServer: async () => {
        const session = get().currentSession;
        const key = get().licenseKey;
        if (!session || !key) return;
        
        set({ serverSyncStatus: "syncing", serverSyncError: null });
        
        try {
          // Check if session already exists on server (has been created there)
          const checkRes = await fetch(`/api/sessions/${session.id}`, {
            headers: { Authorization: `Bearer ${key}` },
          });
          
          if (checkRes.ok) {
            // Session exists — update it
            const res = await fetch(`/api/sessions/${session.id}`, {
              method: "PUT",
              headers: {
                "Content-Type": "application/json",
                Authorization: `Bearer ${key}`,
              },
              body: JSON.stringify({
                tasks: session.tasks.map(stripForServer),
                active: session.active,
                activeTaskId: session.activeTaskId,
                autoAnswerAuditLog: get().autoAnswerAuditLog,
              }),
            });
            if (!res.ok) throw new Error(`Server sync failed (${res.status})`);
          } else {
            // Session doesn't exist yet — create it
            const res = await fetch("/api/sessions", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                Authorization: `Bearer ${key}`,
              },
              body: JSON.stringify({
                name: session.name,
                tasks: session.tasks.map(stripForServer),
              }),
            });
            if (!res.ok) throw new Error(`Server create failed (${res.status})`);
            
            const data = await res.json();
            const serverId = data.session?.id;
            
            // Re-key the local session to match the server-assigned Firestore ID
            // so that future syncs and merges don't create duplicates.
            if (serverId && serverId !== session.id) {
              const rekeyed = { ...session, id: serverId };
              set({
                currentSession: rekeyed as TaskSession,
                sessions: syncSessions(get().sessions, rekeyed as TaskSession),
              });
            }
            
            // If session is confirmed, mark it active on the server
            if (session.confirmed && serverId) {
              await fetch(`/api/sessions/${serverId}`, {
                method: "PUT",
                headers: {
                  "Content-Type": "application/json",
                  Authorization: `Bearer ${key}`,
                },
                body: JSON.stringify({ active: true }),
              });
            }
          }
          
          set({ serverSyncStatus: "idle" });
        } catch (err) {
          console.warn("[Lyceum] Server sync failed (session still saved locally):", err);
          set({
            serverSyncStatus: "error",
            serverSyncError: err instanceof Error ? err.message : "Sync failed",
          });
        }
      },

      // Load all sessions from server
      loadServerSessions: async () => {
        const key = get().licenseKey;
        if (!key) return;
        
        try {
          const res = await fetch("/api/sessions", {
            headers: { Authorization: `Bearer ${key}` },
          });
          if (!res.ok) throw new Error(`Failed to load server sessions (${res.status})`);
          const data = await res.json();
          
          // Merge with local sessions — server wins on conflicts
          const localSessions = get().sessions;
          const serverSessions: TaskSession[] = (data.sessions || []).map((s: any) => ({
            ...s,
            tasks: s.tasks || [],
          } as TaskSession));
          
          // Build a map of id → session, server first
          const merged = new Map<string, TaskSession>();
          for (const s of serverSessions) merged.set(s.id, s);
          for (const s of localSessions) {
            if (!merged.has(s.id)) merged.set(s.id, s);
          }
          
          set({ sessions: Array.from(merged.values()) });
          
          // Restore auto-answer audit log from server data if current session matches
          const current = get().currentSession;
          if (current) {
            const serverMatch = data.sessions?.find((s: any) => s.id === current.id);
            if (serverMatch?.autoAnswerAuditLog) {
              set({ autoAnswerAuditLog: serverMatch.autoAnswerAuditLog });
            }
          }
        } catch (err) {
          console.warn("[Lyceum] Failed to load server sessions:", err);
          // Local sessions still work — don't block the user
        }
      },

      // Confirm and sync to server in one call
      confirmSessionAndSync: async () => {
        const session = get().currentSession;
        if (!session) return;
        
        const updated = { ...session, confirmed: true, active: true };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
          step: "workspace",
        });
        
        // Fire-and-forget server sync — don't block navigation
        get().syncSessionToServer();
      },

      removeTask: (taskId) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = {
          ...session,
          tasks: session.tasks
            .filter((t) => t.id !== taskId)
            // Clean up dangling dependsOn
            .map((t) => ({
              ...t,
              dependsOn: t.dependsOn.filter((d) => d !== taskId),
            })),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      updateTaskTimeframe: (taskId, timeframe) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId ? { ...t, timeframe, estimatedMinutes: parseInt(timeframe) || 30 } : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      assignAIToTask: (taskId, aiRole) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId
              ? { ...t, assignedAIs: [...t.assignedAIs, aiRole] }
              : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      removeAITask: (taskId, roleName) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId
              ? { ...t, assignedAIs: t.assignedAIs.filter((a) => a.roleName !== roleName) }
              : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      confirmSession: () => {
        const session = get().currentSession;
        if (!session) return;
        const updated = { ...session, confirmed: true, active: true };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
          step: "workspace",
        });
      },

      setActiveTask: (taskId) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = { ...session, activeTaskId: taskId };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      submitHumanOutput: (taskId, output) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = {
          ...session,
          tasks: session.tasks.map((t) => {
            if (t.id !== taskId) return t;
            return { ...t, humanOutput: output, status: "completed" as TaskStatus };
          }),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      completeTask: (taskId) => {
        const session = get().currentSession;
        if (!session) return;
        
        const task = session.tasks.find((t) => t.id === taskId);
        if (!task) return;
        
        const updatedTasks = session.tasks.map((t) =>
          t.id === taskId ? { ...t, status: "completed" as TaskStatus } : t
        );
        
        const dependentTasks = updatedTasks.filter((t) =>
          t.dependsOn.includes(taskId)
        );
        
        dependentTasks.forEach((dt) => {
          const allDepsMet = dt.dependsOn.every((depId) =>
            updatedTasks.find((t) => t.id === depId)?.status === "completed"
          );
          if (allDepsMet && dt.status === "not_started") {
            if (dt.assignedAIs.length > 0) {
              dt.status = "awaiting_ai";
            } else {
              dt.status = "in_progress";
            }
          }
        });
        
        const updated = { ...session, tasks: updatedTasks };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      triggerAITask: async (taskId) => {
        const session = get().currentSession;
        if (!session) return;
        const task = session.tasks.find((t) => t.id === taskId);
        if (!task || task.assignedAIs.length === 0) return;
        const max = get().maxAttempts;
        const attemptsSoFar = task.attemptCount ?? 0;

        // Check if max attempts already exhausted
        if (attemptsSoFar >= max) {
          get().markTaskFailed(taskId, `Max attempts (${max}) reached.`);
          return;
        }

        // Generate clarification questions before executing
        get().generateClarificationQuestions(taskId);
        const unanswered = get().getUnansweredQuestions(taskId);
        if (unanswered.length > 0) {
          // Questions need answers — status is now "awaiting_clarification"
          // The answer flow will re-trigger via submitHumanOutput
          return;
        }

        // Mark as ai_working and increment attempt
        get().incrementTaskAttempt(taskId);
        const markWorking = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId ? { ...t, status: "ai_working" as TaskStatus } : t
          ),
        };
        set({
          currentSession: markWorking,
          sessions: syncSessions(get().sessions, markWorking),
        });

        try {
          // Trigger all AI agents sequentially, each with real streaming
          for (const role of task.assignedAIs) {
            await runAgentFn({
              task: get().currentSession?.tasks.find((t) => t.id === taskId)!,
              role,
              onChunk: (chunk) => {
                if (!chunk.done) {
                  get().updateTaskAIOutput(taskId, role.roleName, chunk.accumulated);
                }
              },
            });
          }
          // All agents done — complete the task
          get().completeTask(taskId);
        } catch (err) {
          const errorMsg = err instanceof Error ? err.message : "Agent execution failed";
          console.error("[Lyceum] Agent streaming failed:", err);

          // Track the failure — if under maxAttempts, ask human for approval
          const newAttempts = (get().currentSession?.tasks.find((t) => t.id === taskId)?.attemptCount ?? 1);
          if (newAttempts < max) {
            get().markTaskFailed(taskId, errorMsg);
          } else {
            // Max attempts exhausted — mark permanently failed
            const s = get().currentSession;
            if (s) {
              const failUpdated = {
                ...s,
                tasks: s.tasks.map((t) =>
                  t.id === taskId ? { ...t, status: "failed" as TaskStatus, error: errorMsg } : t
                ),
              };
              set({
                currentSession: failUpdated,
                sessions: syncSessions(get().sessions, failUpdated),
              });
            }
          }
        }
      },

      triggerAIAgent: async (taskId, roleName) => {
        const session = get().currentSession;
        if (!session) return "";
        const task = session.tasks.find((t) => t.id === taskId);
        if (!task) return "";
        const role = task.assignedAIs.find((r) => r.roleName === roleName);
        if (!role) return "";
        const max = get().maxAttempts;
        const attemptsSoFar = task.attemptCount ?? 0;

        if (attemptsSoFar >= max) {
          get().markTaskFailed(taskId, `Max attempts (${max}) reached.`);
          return "";
        }

        // Generate clarification questions before executing
        get().generateClarificationQuestions(taskId);
        const unanswered = get().getUnansweredQuestions(taskId);
        if (unanswered.length > 0) {
          return ""; // questions pending
        }

        // Mark as ai_working + increment attempt
        get().incrementTaskAttempt(taskId);
        if (task.status !== "ai_working") {
          const markWorking = {
            ...session,
            tasks: session.tasks.map((t) =>
              t.id === taskId ? { ...t, status: "ai_working" as TaskStatus } : t
            ),
          };
          set({
            currentSession: markWorking,
            sessions: syncSessions(get().sessions, markWorking),
          });
        }

        try {
          const result = await runAgentFn({
            task: get().currentSession?.tasks.find((t) => t.id === taskId)!,
            role,
            onChunk: (chunk) => {
              if (!chunk.done) {
                get().updateTaskAIOutput(taskId, roleName, chunk.accumulated);
              }
            },
          });
          return result;
        } catch (err) {
          const errorMsg = err instanceof Error ? err.message : "Agent execution failed";
          console.error(`[Lyceum] Agent ${roleName} failed:`, err);

          const newAttempts = (get().currentSession?.tasks.find((t) => t.id === taskId)?.attemptCount ?? 1);
          if (newAttempts < max) {
            get().markTaskFailed(taskId, errorMsg);
          } else {
            const s = get().currentSession;
            if (s) {
              const failUpdated = {
                ...s,
                tasks: s.tasks.map((t) =>
                  t.id === taskId ? { ...t, status: "failed" as TaskStatus, error: errorMsg } : t
                ),
              };
              set({
                currentSession: failUpdated,
                sessions: syncSessions(get().sessions, failUpdated),
              });
            }
          }
          return "";
        }
      },

      updateTaskAIOutput: (taskId, roleName, text) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = {
          ...session,
          tasks: session.tasks.map((t) => {
            if (t.id !== taskId) return t;
            const aiOutputs = { ...(t.aiOutputs || {}) };
            aiOutputs[roleName] = text;
            return {
              ...t,
              aiOutputs,
              // Keep legacy aiOutput as concatenation of all role outputs
              aiOutput: Object.values(aiOutputs).join("\n\n---\n\n"),
            };
          }),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      updateTaskStatus: (taskId, status) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId ? { ...t, status } : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      setSessionActive: (active) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = { ...session, active };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      // ── Clarification Questions ─────────────────────────────────────────

      generateClarificationQuestions: (taskId) => {
        const session = get().currentSession;
        if (!session) return;
        const task = session.tasks.find((t) => t.id === taskId);
        if (!task) return;

        // Don't regenerate if questions already exist (preserves answered ones)
        if (task.clarificationQuestions) return;

        // Generate context-aware MCQ questions based on the task's title,
        // description, and assigned AI roles.
        const questions = generateQuestionsForTask(task);
        if (questions.length === 0) return;

        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId
              ? {
                  ...t,
                  clarificationQuestions: questions,
                  status: "awaiting_clarification" as TaskStatus,
                }
              : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });

        // Start auto-answer timer if enabled
        if (get().autoAnswerEnabled) {
          get().startAutoAnswerTimer(taskId);
        }
      },

      answerClarificationQuestion: (taskId, questionId, answer) => {
        const session = get().currentSession;
        if (!session) return;
        const task = session.tasks.find((t) => t.id === taskId);
        if (!task) return;

        const updatedQuestions = (task.clarificationQuestions ?? []).map((q) =>
          q.id === questionId
            ? { ...q, answer, answeredAt: Date.now(), autoAnswered: false }
            : q
        );
        const allAnswered = updatedQuestions.every((q) => q.answer !== null);

        // Cancel auto-answer timer — human is interacting
        get().cancelAutoAnswerTimer(taskId);

        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId
              ? {
                  ...t,
                  clarificationQuestions: updatedQuestions,
                  // If all questions answered, move back to previous status
                  status: allAnswered
                    ? (t.assignedAIs.length > 0 ? "awaiting_ai" as TaskStatus : "in_progress" as TaskStatus)
                    : "awaiting_clarification" as TaskStatus,
                }
              : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      getUnansweredQuestions: (taskId) => {
        const task = get().currentSession?.tasks.find((t) => t.id === taskId);
        return (task?.clarificationQuestions ?? []).filter((q) => q.answer === null);
      },

      getAllUnansweredQuestions: () => {
        const session = get().currentSession;
        if (!session) return [];
        return session.tasks
          .filter((t) => t.clarificationQuestions?.some((q) => q.answer === null))
          .map((t) => ({
            taskId: t.id,
            taskTitle: t.title,
            questions: (t.clarificationQuestions ?? []).filter((q) => q.answer === null),
          }));
      },

      // ── Auto-answer actions ────────────────────────────────────────────

      setAutoAnswerConfig: (config) => {
        const current = get();
        set({
          autoAnswerEnabled: config.enabled ?? current.autoAnswerEnabled,
          autoAnswerTimeout: config.timeoutMs ?? current.autoAnswerTimeout,
        });
      },

      startAutoAnswerTimer: (taskId) => {
        // Clear any existing timer for this task
        get().cancelAutoAnswerTimer(taskId);

        const timeoutMs = get().autoAnswerTimeout;
        if (timeoutMs <= 0) return;

        const timerId = setTimeout(() => {
          // Auto-answer when timer fires
          get().autoAnswerUnanswered(taskId);
          autoAnswerTimers.delete(taskId);
        }, timeoutMs);

        autoAnswerTimers.set(taskId, {
          timerId,
          startTime: Date.now(),
          durationMs: timeoutMs,
        });
      },

      cancelAutoAnswerTimer: (taskId) => {
        const existing = autoAnswerTimers.get(taskId);
        if (existing) {
          clearTimeout(existing.timerId);
          autoAnswerTimers.delete(taskId);
        }
      },

      getAutoAnswerRemainingMs: (taskId) => {
        const timer = autoAnswerTimers.get(taskId);
        if (!timer) return 0;
        const elapsed = Date.now() - timer.startTime;
        const remaining = timer.durationMs - elapsed;
        return Math.max(0, remaining);
      },

      autoAnswerUnanswered: (taskId) => {
        const session = get().currentSession;
        if (!session) return;
        const task = session.tasks.find((t) => t.id === taskId);
        if (!task) return;
        const questions = task.clarificationQuestions;
        if (!questions) return;

        const unanswered = questions.filter((q) => q.answer === null);
        if (unanswered.length === 0) return;

        // Build audit log entries
        const batchId = `auto-${taskId}-${Date.now()}`;
        const auditEntries: AutoAnswerAuditEntry[] = unanswered.map((q) => ({
          taskId,
          taskTitle: task.title,
          questionId: q.id,
          question: q.question,
          defaultAnswer: getDefaultAnswerForQuestion(q),
          timestamp: Date.now(),
          batchId,
        }));

        // Answer each question with its default
        const defaultOptionId = (q: ClarificationQuestion) => getDefaultOptionId(q);
        const updatedQuestions = questions.map((q) => {
          if (q.answer !== null) return q;
          const defaultId = defaultOptionId(q);
          return {
            ...q,
            answer: defaultId ?? "assumed_default",
            answeredAt: Date.now(),
            autoAnswered: true,
          };
        });

        const allAnswered = updatedQuestions.every((q) => q.answer !== null);

        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId
              ? {
                  ...t,
                  clarificationQuestions: updatedQuestions,
                  // Move back to previous status
                  status: allAnswered
                    ? (t.assignedAIs.length > 0 ? "awaiting_ai" as TaskStatus : "in_progress" as TaskStatus)
                    : "awaiting_clarification" as TaskStatus,
                }
              : t
          ),
        };

        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
          autoAnswerAuditLog: [...get().autoAnswerAuditLog, ...auditEntries],
        });

        // Log audit trail
        console.info(
          `[Lyceum Auto-Answer] Task "${task.title}": ${unanswered.length} question(s) assumed defaults.`,
          auditEntries.map((e) => `  • ${e.question} → "${e.defaultAnswer}"`).join("\n"),
          `\n  Batch: ${batchId}`
        );
      },

      // Query helpers
      getTaskById: (taskId) => {
        return get().currentSession?.tasks.find((t) => t.id === taskId);
      },

      getHumanTasks: () => {
        return get().currentSession?.tasks.filter((t) => t.assignedAIs.length === 0) || [];
      },

      getAITasks: () => {
        return get().currentSession?.tasks.filter((t) => t.assignedAIs.length > 0) || [];
      },

      getTasksReadyForHuman: () => {
        return get().currentSession?.tasks.filter((t) => {
          if (t.status !== "not_started") return false;
          return t.dependsOn.every((depId) => {
            const dep = get().currentSession?.tasks.find((x) => x.id === depId);
            return dep?.status === "completed";
          });
        }) || [];
      },

      addTaskDependency: (taskId, dependsOnId) => {
        const session = get().currentSession;
        if (!session || taskId === dependsOnId) return;
        const wouldCycle = (startId: string, targetId: string): boolean => {
          const task = session.tasks.find((t) => t.id === startId);
          if (!task) return false;
          return task.dependsOn.some((d) => d === targetId || wouldCycle(d, targetId));
        };
        if (wouldCycle(dependsOnId, taskId)) return;

        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId
              ? { ...t, dependsOn: t.dependsOn.includes(dependsOnId) ? t.dependsOn : [...t.dependsOn, dependsOnId] }
              : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      removeTaskDependency: (taskId, dependsOnId) => {
        const session = get().currentSession;
        if (!session) return;
        const updated = {
          ...session,
          tasks: session.tasks.map((t) =>
            t.id === taskId
              ? { ...t, dependsOn: t.dependsOn.filter((d) => d !== dependsOnId) }
              : t
          ),
        };
        set({
          currentSession: updated,
          sessions: syncSessions(get().sessions, updated),
        });
      },

      getDependentTasks: (taskId) => {
        return get().currentSession?.tasks.filter((t) => t.dependsOn.includes(taskId)) || [];
      },
    }),
    {
      name: STORAGE_KEY,
      partialize: (state) => ({
        sessions: state.sessions,
        currentSession: state.currentSession,
        maxAttempts: state.maxAttempts,
        autoAnswerEnabled: state.autoAnswerEnabled,
        autoAnswerTimeout: state.autoAnswerTimeout,
        autoAnswerAuditLog: state.autoAnswerAuditLog,
      }),
    }
  )
);
